import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ coins }) {
  const coinsData = coins.data

  const formatePercent = number => 
  `${new Number(number).toFixed(2)}%`

  const formatDollar = (number, maximumSignificantDigits) =>
  new Intl.NumberFormat(
    'en-US', 
    { 
      style: 'currency', 
      currency: 'USD',
      maximumSignificantDigits
    })
    .format(number);


  return ( 
    <div className={styles.container}>
      <Head>
        <title>top100-token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <h1 className='text-center'>top100-token</h1>

      <table className='table table-dark'>
        <thead>
          <tr>
            <th>Name</th>
            <th>Symbol</th>
            <th>24H Change</th>
            <th>Price</th>
            <th>Market Cap</th>
          </tr>
        </thead>
        <tbody>
          {coinsData.map(coin => (
            <tr>
              <td>
                {coin.name.toUpperCase()}
              </td>    
              <td>
                {coin.symbol.toUpperCase()}
              </td>
              <td>
                <span
                  className={coin.quote.USD.percent_change_24h > 0 ? (
                    'text-success'
                  ) : 'text-danger'}  
                >
                  {formatePercent(coin.quote.USD.percent_change_24h)}
                </span>      
              </td>
              <td>
                {formatDollar(coin.quote.USD.price)}
              </td>
              <td>
                {formatDollar(coin.quote.USD.market_cap)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

export async function getServerSideProps(context) {
  const coins = await fetch(
    "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest",
    {
      method: "GET",
      headers: { "X-CMC_PRO_API_KEY": process.env.authAPIkey },
    }
  ).then((res) => res.json());

  return {
    props: { coins },
  };
}
